version: "3.9"

services:
  api:
    build: .
    ports: 
      - "4000:4000"
    command: node src/index.js
    env_file: 
      - p.env
    depends_on: 
      - redis
      - mongo

  redis:
    image: redis:6.2.5-alpine
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo:5-focal
    restart: always
    volumes:
      - mongo-data:/data/db
    ports: 
      - "27018:27017"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: on-failure
volumes: 
  mongo-data:
  redis-data: