version: "3.9"
   
services:
  syslog-ng:
    image: balabit/syslog-ng
    volumes: 
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
  nginx:
    image: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - syslog-ng